# Global typed signals — UI and systems subscribe without tight coupling.
extends Node

@warning_ignore("unused_signal")
signal turn_advanced(state: RunState)
@warning_ignore("unused_signal")
signal command_applied(command_name: String, state: RunState)
@warning_ignore("unused_signal")
signal run_started(state: RunState)
@warning_ignore("unused_signal")
signal run_loaded(state: RunState)
@warning_ignore("unused_signal")
signal asset_acquired(asset_type: String, asset_id: String)
@warning_ignore("unused_signal")
signal negotiation_started(state: RunState)
@warning_ignore("unused_signal")
signal negotiation_ended(state: RunState)
@warning_ignore("unused_signal")
signal negotiation_updated(state: RunState)
@warning_ignore("unused_signal")
signal run_ended(state: RunState)

## Turn pipeline domain events (emitted after advance_turn).
@warning_ignore("unused_signal")
signal turn_debrief_ready(state: RunState, debrief: Dictionary)
@warning_ignore("unused_signal")
signal milestone_reached(state: RunState, milestone_id: String)
@warning_ignore("unused_signal")
signal edge_choices_pending(state: RunState, choices: Array)
@warning_ignore("unused_signal")
signal supply_shortage_detected(state: RunState, shortages: Array)
@warning_ignore("unused_signal")
signal districts_unlocked(state: RunState, district_ids: Array)
@warning_ignore("unused_signal")
signal map_state_changed(state: RunState)
